remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [hackpack]
description: [hackpack is a website containing all my materials, tools, and books that I use on a day-to-day basis]
